In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df=pd.DataFrame({'color':['red','blue','green','green','red','blue']})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [5]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\preet\anaconda3\envs\practise_env\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [6]:
lbl_encoder.transform([['red']])

c:\Users\preet\anaconda3\envs\practise_env\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [7]:
lbl_encoder.transform([['blue']])

c:\Users\preet\anaconda3\envs\practise_env\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [8]:
lbl_encoder.transform([['green']])

c:\Users\preet\anaconda3\envs\practise_env\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [19]:
## ordinal encoding

from sklearn.preprocessing import OrdinalEncoder

df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})


encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [20]:
df.head()

     size
0   small
1  medium
2   large
3  medium
4   small

In [22]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [23]:
encoder.transform([['small']])

c:\Users\preet\anaconda3\envs\practise_env\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])